# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\"\"\n\x0cQueryRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"9\n\rQueryResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12\x11\n\tai_source\x18\x02 \x01(\t2:\n\tAIService\x12-\n\x0cProcessQuery\x12\r.QueryRequest\x1a\x0e.QueryResponseB\x0f\xaa\x02\x0c\x41ICoreClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014AICoreClient'
  _globals['_QUERYREQUEST']._serialized_start=20
  _globals['_QUERYREQUEST']._serialized_end=54
  _globals['_QUERYRESPONSE']._serialized_start=56
  _globals['_QUERYRESPONSE']._serialized_end=113
  _globals['_AISERVICE']._serialized_start=115
  _globals['_AISERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
