# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import runtime_contract_pb2 as runtime__contract__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in runtime_contract_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Target contract for the modular runtime. This file is intentionally separate
    from ai_service.proto so the current UI remains compatible while services are
    extracted.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCapabilities = channel.unary_unary(
                '/RuntimeService/ListCapabilities',
                request_serializer=runtime__contract__pb2.ListCapabilitiesRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.ListCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetCapabilitySchema = channel.unary_unary(
                '/RuntimeService/GetCapabilitySchema',
                request_serializer=runtime__contract__pb2.CapabilityRef.SerializeToString,
                response_deserializer=runtime__contract__pb2.CapabilitySchema.FromString,
                _registered_method=True)
        self.RunCapability = channel.unary_unary(
                '/RuntimeService/RunCapability',
                request_serializer=runtime__contract__pb2.RunCapabilityRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.RunCapabilityResponse.FromString,
                _registered_method=True)
        self.StreamCapabilityEvents = channel.unary_stream(
                '/RuntimeService/StreamCapabilityEvents',
                request_serializer=runtime__contract__pb2.RunRef.SerializeToString,
                response_deserializer=runtime__contract__pb2.CapabilityEvent.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/RuntimeService/CancelRun',
                request_serializer=runtime__contract__pb2.RunRef.SerializeToString,
                response_deserializer=runtime__contract__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/RuntimeService/HealthCheck',
                request_serializer=runtime__contract__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Target contract for the modular runtime. This file is intentionally separate
    from ai_service.proto so the current UI remains compatible while services are
    extracted.

    """

    def ListCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilitySchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCapabilityEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCapabilities,
                    request_deserializer=runtime__contract__pb2.ListCapabilitiesRequest.FromString,
                    response_serializer=runtime__contract__pb2.ListCapabilitiesResponse.SerializeToString,
            ),
            'GetCapabilitySchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilitySchema,
                    request_deserializer=runtime__contract__pb2.CapabilityRef.FromString,
                    response_serializer=runtime__contract__pb2.CapabilitySchema.SerializeToString,
            ),
            'RunCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCapability,
                    request_deserializer=runtime__contract__pb2.RunCapabilityRequest.FromString,
                    response_serializer=runtime__contract__pb2.RunCapabilityResponse.SerializeToString,
            ),
            'StreamCapabilityEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCapabilityEvents,
                    request_deserializer=runtime__contract__pb2.RunRef.FromString,
                    response_serializer=runtime__contract__pb2.CapabilityEvent.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=runtime__contract__pb2.RunRef.FromString,
                    response_serializer=runtime__contract__pb2.CancelRunResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=runtime__contract__pb2.HealthCheckRequest.FromString,
                    response_serializer=runtime__contract__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Target contract for the modular runtime. This file is intentionally separate
    from ai_service.proto so the current UI remains compatible while services are
    extracted.

    """

    @staticmethod
    def ListCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeService/ListCapabilities',
            runtime__contract__pb2.ListCapabilitiesRequest.SerializeToString,
            runtime__contract__pb2.ListCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilitySchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeService/GetCapabilitySchema',
            runtime__contract__pb2.CapabilityRef.SerializeToString,
            runtime__contract__pb2.CapabilitySchema.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeService/RunCapability',
            runtime__contract__pb2.RunCapabilityRequest.SerializeToString,
            runtime__contract__pb2.RunCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCapabilityEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/RuntimeService/StreamCapabilityEvents',
            runtime__contract__pb2.RunRef.SerializeToString,
            runtime__contract__pb2.CapabilityEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeService/CancelRun',
            runtime__contract__pb2.RunRef.SerializeToString,
            runtime__contract__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeService/HealthCheck',
            runtime__contract__pb2.HealthCheckRequest.SerializeToString,
            runtime__contract__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RuntimeMemoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchMemory = channel.unary_unary(
                '/RuntimeMemoryService/SearchMemory',
                request_serializer=runtime__contract__pb2.MemorySearchRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.MemorySearchResponse.FromString,
                _registered_method=True)
        self.IndexProjectMemory = channel.unary_unary(
                '/RuntimeMemoryService/IndexProjectMemory',
                request_serializer=runtime__contract__pb2.IndexProjectMemoryRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.IndexProjectMemoryResponse.FromString,
                _registered_method=True)
        self.RecentToolRuns = channel.unary_unary(
                '/RuntimeMemoryService/RecentToolRuns',
                request_serializer=runtime__contract__pb2.RecentToolRunsRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.RecentToolRunsResponse.FromString,
                _registered_method=True)
        self.RecentExecutionPlans = channel.unary_unary(
                '/RuntimeMemoryService/RecentExecutionPlans',
                request_serializer=runtime__contract__pb2.RecentExecutionPlansRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.RecentExecutionPlansResponse.FromString,
                _registered_method=True)
        self.GetMemoryStats = channel.unary_unary(
                '/RuntimeMemoryService/GetMemoryStats',
                request_serializer=runtime__contract__pb2.MemoryStatsRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.MemoryStatsResponse.FromString,
                _registered_method=True)


class RuntimeMemoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexProjectMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecentToolRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecentExecutionPlans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeMemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=runtime__contract__pb2.MemorySearchRequest.FromString,
                    response_serializer=runtime__contract__pb2.MemorySearchResponse.SerializeToString,
            ),
            'IndexProjectMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexProjectMemory,
                    request_deserializer=runtime__contract__pb2.IndexProjectMemoryRequest.FromString,
                    response_serializer=runtime__contract__pb2.IndexProjectMemoryResponse.SerializeToString,
            ),
            'RecentToolRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.RecentToolRuns,
                    request_deserializer=runtime__contract__pb2.RecentToolRunsRequest.FromString,
                    response_serializer=runtime__contract__pb2.RecentToolRunsResponse.SerializeToString,
            ),
            'RecentExecutionPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.RecentExecutionPlans,
                    request_deserializer=runtime__contract__pb2.RecentExecutionPlansRequest.FromString,
                    response_serializer=runtime__contract__pb2.RecentExecutionPlansResponse.SerializeToString,
            ),
            'GetMemoryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryStats,
                    request_deserializer=runtime__contract__pb2.MemoryStatsRequest.FromString,
                    response_serializer=runtime__contract__pb2.MemoryStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RuntimeMemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RuntimeMemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeMemoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeMemoryService/SearchMemory',
            runtime__contract__pb2.MemorySearchRequest.SerializeToString,
            runtime__contract__pb2.MemorySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexProjectMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeMemoryService/IndexProjectMemory',
            runtime__contract__pb2.IndexProjectMemoryRequest.SerializeToString,
            runtime__contract__pb2.IndexProjectMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecentToolRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeMemoryService/RecentToolRuns',
            runtime__contract__pb2.RecentToolRunsRequest.SerializeToString,
            runtime__contract__pb2.RecentToolRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecentExecutionPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeMemoryService/RecentExecutionPlans',
            runtime__contract__pb2.RecentExecutionPlansRequest.SerializeToString,
            runtime__contract__pb2.RecentExecutionPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemoryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeMemoryService/GetMemoryStats',
            runtime__contract__pb2.MemoryStatsRequest.SerializeToString,
            runtime__contract__pb2.MemoryStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RuntimeModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModels = channel.unary_unary(
                '/RuntimeModelService/ListModels',
                request_serializer=runtime__contract__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/RuntimeModelService/GetModelStatus',
                request_serializer=runtime__contract__pb2.ModelRef.SerializeToString,
                response_deserializer=runtime__contract__pb2.ModelStatusResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/RuntimeModelService/LoadModel',
                request_serializer=runtime__contract__pb2.ModelRef.SerializeToString,
                response_deserializer=runtime__contract__pb2.ModelActionResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/RuntimeModelService/UnloadModel',
                request_serializer=runtime__contract__pb2.ModelRef.SerializeToString,
                response_deserializer=runtime__contract__pb2.ModelActionResponse.FromString,
                _registered_method=True)
        self.ProbeModel = channel.unary_unary(
                '/RuntimeModelService/ProbeModel',
                request_serializer=runtime__contract__pb2.ModelProbeRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.ModelProbeResponse.FromString,
                _registered_method=True)


class RuntimeModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=runtime__contract__pb2.ListModelsRequest.FromString,
                    response_serializer=runtime__contract__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=runtime__contract__pb2.ModelRef.FromString,
                    response_serializer=runtime__contract__pb2.ModelStatusResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=runtime__contract__pb2.ModelRef.FromString,
                    response_serializer=runtime__contract__pb2.ModelActionResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=runtime__contract__pb2.ModelRef.FromString,
                    response_serializer=runtime__contract__pb2.ModelActionResponse.SerializeToString,
            ),
            'ProbeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ProbeModel,
                    request_deserializer=runtime__contract__pb2.ModelProbeRequest.FromString,
                    response_serializer=runtime__contract__pb2.ModelProbeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RuntimeModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RuntimeModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeModelService/ListModels',
            runtime__contract__pb2.ListModelsRequest.SerializeToString,
            runtime__contract__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeModelService/GetModelStatus',
            runtime__contract__pb2.ModelRef.SerializeToString,
            runtime__contract__pb2.ModelStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeModelService/LoadModel',
            runtime__contract__pb2.ModelRef.SerializeToString,
            runtime__contract__pb2.ModelActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeModelService/UnloadModel',
            runtime__contract__pb2.ModelRef.SerializeToString,
            runtime__contract__pb2.ModelActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RuntimeModelService/ProbeModel',
            runtime__contract__pb2.ModelProbeRequest.SerializeToString,
            runtime__contract__pb2.ModelProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VoiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecognizeSpeech = channel.stream_stream(
                '/VoiceService/StreamRecognizeSpeech',
                request_serializer=runtime__contract__pb2.AudioChunk.SerializeToString,
                response_deserializer=runtime__contract__pb2.SpeechRecognitionEvent.FromString,
                _registered_method=True)
        self.Speak = channel.unary_unary(
                '/VoiceService/Speak',
                request_serializer=runtime__contract__pb2.SpeakRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.SpeakResponse.FromString,
                _registered_method=True)
        self.InterruptSpeech = channel.unary_unary(
                '/VoiceService/InterruptSpeech',
                request_serializer=runtime__contract__pb2.InterruptSpeechRequest.SerializeToString,
                response_deserializer=runtime__contract__pb2.InterruptSpeechResponse.FromString,
                _registered_method=True)


class VoiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamRecognizeSpeech(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Speak(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterruptSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRecognizeSpeech': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRecognizeSpeech,
                    request_deserializer=runtime__contract__pb2.AudioChunk.FromString,
                    response_serializer=runtime__contract__pb2.SpeechRecognitionEvent.SerializeToString,
            ),
            'Speak': grpc.unary_unary_rpc_method_handler(
                    servicer.Speak,
                    request_deserializer=runtime__contract__pb2.SpeakRequest.FromString,
                    response_serializer=runtime__contract__pb2.SpeakResponse.SerializeToString,
            ),
            'InterruptSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.InterruptSpeech,
                    request_deserializer=runtime__contract__pb2.InterruptSpeechRequest.FromString,
                    response_serializer=runtime__contract__pb2.InterruptSpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VoiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VoiceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamRecognizeSpeech(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/VoiceService/StreamRecognizeSpeech',
            runtime__contract__pb2.AudioChunk.SerializeToString,
            runtime__contract__pb2.SpeechRecognitionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Speak(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VoiceService/Speak',
            runtime__contract__pb2.SpeakRequest.SerializeToString,
            runtime__contract__pb2.SpeakResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InterruptSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VoiceService/InterruptSpeech',
            runtime__contract__pb2.InterruptSpeechRequest.SerializeToString,
            runtime__contract__pb2.InterruptSpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
